version: '3.8'
services:
  user-database:
    container_name: user-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    ports:
      - "5433:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
